sudo: required
services: docker
language: bash
env:
    global:
        - QEMU_VER=v2.9.1
        - DOCKER_REPO=maartje/dispatch
    matrix:
        - ARCH=amd64    VERSION=0.0.7    QEMU_ARCH=x86_64   TAG_VERSION=0.0.7   DOCKER_ARCH_BASE=amd64/
        - ARCH=armhf    VERSION=0.0.7    QEMU_ARCH=arm      TAG_VERSION=0.0.7   DOCKER_ARCH_BASE=armhf/

        - ARCH=amd64    VERSION=0.0.8    QEMU_ARCH=x86_64   TAG_VERSION=0.0.8   DOCKER_ARCH_BASE=amd64/
        - ARCH=armhf    VERSION=0.0.8    QEMU_ARCH=arm      TAG_VERSION=0.0.8   DOCKER_ARCH_BASE=armhf/

        - ARCH=amd64    VERSION=0.0.8    QEMU_ARCH=x86_64   TAG_VERSION=latest  DOCKER_ARCH_BASE=amd64/
        - ARCH=armhf    VERSION=0.0.8    QEMU_ARCH=arm      TAG_VERSION=latest  aDOCKER_ARCH_BASE=armhf/

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

before_script:
    - sudo apt-get -y install qemu-user-static
    - docker run --rm --privileged multiarch/qemu-user-static:register
script:
    - sudo ./build.sh --arch="$ARCH" --version="$VERSION" --qemuarch="$QEMU_ARCH" --qemuversion="$QEMU_VER" --repo="$DOCKER_REPO" --dockerarchbase="$DOCKER_ARCH_BASE" --tagversion="$TAG_VERSION" 
after_success:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push $DOCKER_REPO